sudo: required

language: python

services:
  - docker

python:
  - 3.5


before_install:
  - sed -i '1i'"127.0.0.1 citadel.ucsd.edu" /etc/hosts
  - cp test/config.py app/config.py
  - docker pull influxdb
  - docker run --name citadel-influxdb -itd influxdb
  - docker pull mongo
  - docker run --name citadel-mongodb -itd mongo
  - docker build -t jbkoh/citadel .
  - docker run -itd -p 127.0.0.1:8080:80 --name citade-instance jbkoh/citadel
  
script:
  python test/rest_api_test.py
